<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <AssemblyVersion>0.0.1.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Abstractions\FormListBase.cs" />
    <Compile Remove="Builders\FieldBuilder.cs" />
    <Compile Remove="Builders\FormBuilderBase.cs" />
    <Compile Remove="Builders\FormCardListTypeBuilder.cs" />
    <Compile Remove="Builders\FormEntityTypeBuilder.cs" />
    <Compile Remove="Builders\FormListBuilder.cs" />
    <Compile Remove="Builders\FormListTypeBuilder.cs" />
    <Compile Remove="Builders\FormRepeaterTypeBuilder.cs" />
    <Compile Remove="Builders\RepeaterFieldBuilder.cs" />
  </ItemGroup>

</Project>
